import { MaterialTheme, ThemeMode } from '../types';

export interface ThemeColors {
  primary: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  surface: string;
  surfaceDim: string;
  surfaceBright: string;
  surfaceContainerLowest: string;
  surfaceContainerLow: string;
  surfaceContainer: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
  onSurface: string;
  onSurfaceVariant: string;
  outline: string;
  outlineVariant: string;
  error: string;
  errorContainer: string;
  onErrorContainer: string;
  accentJournal: string;
  accentStudy: string;
  accentRecovery: string;
  accentFinance: string;
  accentPulse: string;
  accentGoals: string;
}

export const THEME_PALETTES: Record<MaterialTheme, { name: string; icon: string; seed: string; light: ThemeColors; dark: ThemeColors }> = {
  botanical: {
    name: 'Botanical Sage',
    icon: '🌿',
    seed: '#2F6B4F',
    light: {
      primary: '#2D6A4F',
      onPrimary: '#FFFFFF',
      primaryContainer: '#D8F3DC',
      onPrimaryContainer: '#081C15',
      secondary: '#40916C',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#B7E4C7',
      onSecondaryContainer: '#1B4332',
      tertiary: '#D4A373',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#FAEDCD',
      onTertiaryContainer: '#582F0E',
      surface: '#F8F9F5',
      surfaceDim: '#EDEDE8',
      surfaceBright: '#FFFFFF',
      surfaceContainerLowest: '#FFFFFF',
      surfaceContainerLow: '#F4F5F0',
      surfaceContainer: '#EAECE6',
      surfaceContainerHigh: '#E2E5DD',
      surfaceContainerHighest: '#DADED5',
      onSurface: '#191C1A',
      onSurfaceVariant: '#404943',
      outline: '#707973',
      outlineVariant: '#BFC9C2',
      error: '#BA1A1A',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
      accentJournal: '#2D6A4F',
      accentStudy: '#1B4332',
      accentRecovery: '#D4A373',
      accentFinance: '#3A86C8',
      accentPulse: '#C94C76',
      accentGoals: '#D97706',
    },
    dark: {
      primary: '#95D5B2',
      onPrimary: '#081C15',
      primaryContainer: '#1B4332',
      onPrimaryContainer: '#D8F3DC',
      secondary: '#74C69D',
      onSecondary: '#081C15',
      secondaryContainer: '#2D6A4F',
      onSecondaryContainer: '#B7E4C7',
      tertiary: '#E9D8A6',
      onTertiary: '#3E2723',
      tertiaryContainer: '#5F4619',
      onTertiaryContainer: '#FFE8A3',
      surface: '#111412',
      surfaceDim: '#111412',
      surfaceBright: '#373A37',
      surfaceContainerLowest: '#0C0F0D',
      surfaceContainerLow: '#191C1A',
      surfaceContainer: '#1D211E',
      surfaceContainerHigh: '#282B28',
      surfaceContainerHighest: '#333633',
      onSurface: '#E1E3DF',
      onSurfaceVariant: '#BFC9C2',
      outline: '#8A938C',
      outlineVariant: '#404943',
      error: '#FFB4AB',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
      accentJournal: '#95D5B2',
      accentStudy: '#74C69D',
      accentRecovery: '#F0D28A',
      accentFinance: '#90CAF9',
      accentPulse: '#F48FB1',
      accentGoals: '#FBBF24',
    },
  },
  ocean: {
    name: 'Ocean Mist',
    icon: '🌊',
    seed: '#1A73E8',
    light: {
      primary: '#1A73E8',
      onPrimary: '#FFFFFF',
      primaryContainer: '#D2E3FC',
      onPrimaryContainer: '#041E49',
      secondary: '#00796B',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#B2DFDB',
      onSecondaryContainer: '#004D40',
      tertiary: '#7B1FA2',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#E1BEE7',
      onTertiaryContainer: '#4A148C',
      surface: '#F8F9FA',
      surfaceDim: '#EDEEF0',
      surfaceBright: '#FFFFFF',
      surfaceContainerLowest: '#FFFFFF',
      surfaceContainerLow: '#F1F3F5',
      surfaceContainer: '#E8EAED',
      surfaceContainerHigh: '#E1E3E6',
      surfaceContainerHighest: '#DADBDE',
      onSurface: '#202124',
      onSurfaceVariant: '#5F6368',
      outline: '#7F868E',
      outlineVariant: '#BDC1C6',
      error: '#BA1A1A',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
      accentJournal: '#00897B',
      accentStudy: '#1E88E5',
      accentRecovery: '#FB8C00',
      accentFinance: '#0288D1',
      accentPulse: '#E91E63',
      accentGoals: '#F59E0B',
    },
    dark: {
      primary: '#8AB4F8',
      onPrimary: '#041E49',
      primaryContainer: '#174EA6',
      onPrimaryContainer: '#D2E3FC',
      secondary: '#80CBC4',
      onSecondary: '#00332C',
      secondaryContainer: '#004D40',
      onSecondaryContainer: '#B2DFDB',
      tertiary: '#CE93D8',
      onTertiary: '#38006B',
      tertiaryContainer: '#6A1B9A',
      onTertiaryContainer: '#F3E5F5',
      surface: '#121316',
      surfaceDim: '#121316',
      surfaceBright: '#36393F',
      surfaceContainerLowest: '#0D0E11',
      surfaceContainerLow: '#1A1C20',
      surfaceContainer: '#1F2126',
      surfaceContainerHigh: '#2A2C32',
      surfaceContainerHighest: '#35383E',
      onSurface: '#E8EAED',
      onSurfaceVariant: '#BDC1C6',
      outline: '#8A9098',
      outlineVariant: '#43464D',
      error: '#FFB4AB',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
      accentJournal: '#80CBC4',
      accentStudy: '#8AB4F8',
      accentRecovery: '#FFB74D',
      accentFinance: '#4FC3F7',
      accentPulse: '#F06292',
      accentGoals: '#FCD34D',
    },
  },
  terracotta: {
    name: 'Amber Clay',
    icon: '🏺',
    seed: '#A34823',
    light: {
      primary: '#9C411E',
      onPrimary: '#FFFFFF',
      primaryContainer: '#FFDBCE',
      onPrimaryContainer: '#380D00',
      secondary: '#77574B',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#FFDBCE',
      onSecondaryContainer: '#2C160D',
      tertiary: '#6A5F2F',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#F4E3A6',
      onTertiaryContainer: '#221B00',
      surface: '#FFF8F5',
      surfaceDim: '#E7DFDC',
      surfaceBright: '#FFF8F5',
      surfaceContainerLowest: '#FFFFFF',
      surfaceContainerLow: '#FBF1ED',
      surfaceContainer: '#F5EBE7',
      surfaceContainerHigh: '#EFE5E1',
      surfaceContainerHighest: '#E9E0DB',
      onSurface: '#221A17',
      onSurfaceVariant: '#53433E',
      outline: '#85736D',
      outlineVariant: '#D8C2BB',
      error: '#BA1A1A',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
      accentJournal: '#2E7D32',
      accentStudy: '#00796B',
      accentRecovery: '#D97706',
      accentFinance: '#1976D2',
      accentPulse: '#C2185B',
      accentGoals: '#E65100',
    },
    dark: {
      primary: '#FFB59B',
      onPrimary: '#5D1900',
      primaryContainer: '#7D2B09',
      onPrimaryContainer: '#FFDBCE',
      secondary: '#E7BDB0',
      onSecondary: '#442A20',
      secondaryContainer: '#5D3F35',
      onSecondaryContainer: '#FFDBCE',
      tertiary: '#D7C78C',
      onTertiary: '#3A3005',
      tertiaryContainer: '#524719',
      onTertiaryContainer: '#F4E3A6',
      surface: '#1A110E',
      surfaceDim: '#1A110E',
      surfaceBright: '#423733',
      surfaceContainerLowest: '#140C09',
      surfaceContainerLow: '#221916',
      surfaceContainer: '#271D1A',
      surfaceContainerHigh: '#322724',
      surfaceContainerHighest: '#3D322E',
      onSurface: '#F0DFDA',
      onSurfaceVariant: '#D8C2BB',
      outline: '#A08C86',
      outlineVariant: '#53433E',
      error: '#FFB4AB',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
      accentJournal: '#81C784',
      accentStudy: '#4DB6AC',
      accentRecovery: '#FBBF24',
      accentFinance: '#64B5F6',
      accentPulse: '#F06292',
      accentGoals: '#FB923C',
    },
  },
  lavender: {
    name: 'Velvet Orchid',
    icon: '🔮',
    seed: '#6750A4',
    light: {
      primary: '#6750A4',
      onPrimary: '#FFFFFF',
      primaryContainer: '#EADDFF',
      onPrimaryContainer: '#21005D',
      secondary: '#625B71',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#E8DEF8',
      onSecondaryContainer: '#1D192B',
      tertiary: '#7D5260',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#FFD8E4',
      onTertiaryContainer: '#31111D',
      surface: '#FEF7FF',
      surfaceDim: '#DED8E1',
      surfaceBright: '#FEF7FF',
      surfaceContainerLowest: '#FFFFFF',
      surfaceContainerLow: '#F7F2FA',
      surfaceContainer: '#F3EDF7',
      surfaceContainerHigh: '#ECE6F0',
      surfaceContainerHighest: '#E6E0E9',
      onSurface: '#1D1B20',
      onSurfaceVariant: '#49454F',
      outline: '#79747E',
      outlineVariant: '#CAC4D0',
      error: '#B3261E',
      errorContainer: '#F9DEDC',
      onErrorContainer: '#410E0B',
      accentJournal: '#00897B',
      accentStudy: '#5E35B1',
      accentRecovery: '#D97706',
      accentFinance: '#039BE5',
      accentPulse: '#D81B60',
      accentGoals: '#8E24AA',
    },
    dark: {
      primary: '#D0BCFF',
      onPrimary: '#381E72',
      primaryContainer: '#4F378B',
      onPrimaryContainer: '#EADDFF',
      secondary: '#CCC2DC',
      onSecondary: '#332D41',
      secondaryContainer: '#4A4458',
      onSecondaryContainer: '#E8DEF8',
      tertiary: '#EFB8C8',
      onTertiary: '#492532',
      tertiaryContainer: '#633B48',
      onTertiaryContainer: '#FFD8E4',
      surface: '#141218',
      surfaceDim: '#141218',
      surfaceBright: '#3B383E',
      surfaceContainerLowest: '#0F0D13',
      surfaceContainerLow: '#1D1B20',
      surfaceContainer: '#211F26',
      surfaceContainerHigh: '#2B2930',
      surfaceContainerHighest: '#36343B',
      onSurface: '#E6E0E9',
      onSurfaceVariant: '#CAC4D0',
      outline: '#938F99',
      outlineVariant: '#49454F',
      error: '#F2B8B5',
      errorContainer: '#8C1D18',
      onErrorContainer: '#F9DEDC',
      accentJournal: '#4DB6AC',
      accentStudy: '#B39DDB',
      accentRecovery: '#FBBF24',
      accentFinance: '#81D4FA',
      accentPulse: '#F48FB1',
      accentGoals: '#CE93D8',
    },
  },
  rose: {
    name: 'Rose Quartz',
    icon: '🌸',
    seed: '#B91C50',
    light: {
      primary: '#A02048',
      onPrimary: '#FFFFFF',
      primaryContainer: '#FFD9E2',
      onPrimaryContainer: '#3B071D',
      secondary: '#74565F',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#FFD9E2',
      onSecondaryContainer: '#2B151C',
      tertiary: '#7C5635',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#FFDCC1',
      onTertiaryContainer: '#2E1500',
      surface: '#FFF8F8',
      surfaceDim: '#E7DFDF',
      surfaceBright: '#FFF8F8',
      surfaceContainerLowest: '#FFFFFF',
      surfaceContainerLow: '#FBF1F1',
      surfaceContainer: '#F6EBEB',
      surfaceContainerHigh: '#F0E5E5',
      surfaceContainerHighest: '#EAE0E0',
      onSurface: '#211A1B',
      onSurfaceVariant: '#514347',
      outline: '#847377',
      outlineVariant: '#D5C2C6',
      error: '#BA1A1A',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
      accentJournal: '#2E7D32',
      accentStudy: '#8E24AA',
      accentRecovery: '#E65100',
      accentFinance: '#00838F',
      accentPulse: '#D81B60',
      accentGoals: '#C2185B',
    },
    dark: {
      primary: '#FFB1C8',
      onPrimary: '#62002B',
      primaryContainer: '#830839',
      onPrimaryContainer: '#FFD9E2',
      secondary: '#E3BDC6',
      onSecondary: '#422931',
      secondaryContainer: '#5B3F47',
      onSecondaryContainer: '#FFD9E2',
      tertiary: '#EFBD94',
      onTertiary: '#462A0C',
      tertiaryContainer: '#613F1F',
      onTertiaryContainer: '#FFDCC1',
      surface: '#1A1113',
      surfaceDim: '#1A1113',
      surfaceBright: '#423739',
      surfaceContainerLowest: '#140C0E',
      surfaceContainerLow: '#22191B',
      surfaceContainer: '#271D1F',
      surfaceContainerHigh: '#32282A',
      surfaceContainerHighest: '#3D3235',
      onSurface: '#EFE0E1',
      onSurfaceVariant: '#D5C2C6',
      outline: '#9E8C90',
      outlineVariant: '#514347',
      error: '#FFB4AB',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
      accentJournal: '#81C784',
      accentStudy: '#CE93D8',
      accentRecovery: '#FFB74D',
      accentFinance: '#4DD0E1',
      accentPulse: '#F48FB1',
      accentGoals: '#F06292',
    },
  },
  monochrome: {
    name: 'Minimal Ink',
    icon: '🖤',
    seed: '#303030',
    light: {
      primary: '#1E1E1E',
      onPrimary: '#FFFFFF',
      primaryContainer: '#E3E3E3',
      onPrimaryContainer: '#121212',
      secondary: '#5E5E5E',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#E8E8E8',
      onSecondaryContainer: '#1A1A1A',
      tertiary: '#484848',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#DCDCDC',
      onTertiaryContainer: '#141414',
      surface: '#FAF9F6',
      surfaceDim: '#ECEBE7',
      surfaceBright: '#FFFFFF',
      surfaceContainerLowest: '#FFFFFF',
      surfaceContainerLow: '#F3F2EE',
      surfaceContainer: '#ECEBE7',
      surfaceContainerHigh: '#E5E4E0',
      surfaceContainerHighest: '#DEDDD9',
      onSurface: '#191919',
      onSurfaceVariant: '#444444',
      outline: '#757575',
      outlineVariant: '#CCCCCC',
      error: '#BA1A1A',
      errorContainer: '#FFDAD6',
      onErrorContainer: '#410002',
      accentJournal: '#2E7D32',
      accentStudy: '#3949AB',
      accentRecovery: '#E65100',
      accentFinance: '#00838F',
      accentPulse: '#C2185B',
      accentGoals: '#5E35B1',
    },
    dark: {
      primary: '#E2E2E2',
      onPrimary: '#1E1E1E',
      primaryContainer: '#3B3B3B',
      onPrimaryContainer: '#F0F0F0',
      secondary: '#C6C6C6',
      onSecondary: '#2C2C2C',
      secondaryContainer: '#444444',
      onSecondaryContainer: '#E0E0E0',
      tertiary: '#B0B0B0',
      onTertiary: '#242424',
      tertiaryContainer: '#3D3D3D',
      onTertiaryContainer: '#D5D5D5',
      surface: '#121212',
      surfaceDim: '#121212',
      surfaceBright: '#383838',
      surfaceContainerLowest: '#0E0E0E',
      surfaceContainerLow: '#1A1A1A',
      surfaceContainer: '#202020',
      surfaceContainerHigh: '#2B2B2B',
      surfaceContainerHighest: '#333333',
      onSurface: '#E6E6E6',
      onSurfaceVariant: '#C4C4C4',
      outline: '#8E8E8E',
      outlineVariant: '#464646',
      error: '#FFB4AB',
      errorContainer: '#93000A',
      onErrorContainer: '#FFDAD6',
      accentJournal: '#81C784',
      accentStudy: '#9FA8DA',
      accentRecovery: '#FFB74D',
      accentFinance: '#80DEEA',
      accentPulse: '#F48FB1',
      accentGoals: '#B39DDB',
    },
  },
};

export function applyThemeVariables(palette: MaterialTheme, mode: ThemeMode) {
  const isDark =
    mode === 'dark' ||
    (mode === 'system' && typeof window !== 'undefined' && window.matchMedia('(prefers-color-scheme: dark)').matches);

  const paletteDef = THEME_PALETTES[palette] || THEME_PALETTES.botanical;
  const colors = paletteDef[isDark ? 'dark' : 'light'];
  const root = document.documentElement;

  if (isDark) {
    root.classList.add('dark');
  } else {
    root.classList.remove('dark');
  }

  // Inject CSS variables
  Object.entries(colors).forEach(([key, value]) => {
    // Convert camelCase to kebab-case (e.g. primaryContainer -> --md-sys-color-primary-container)
    const kebab = key.replace(/([A-Z])/g, '-$1').toLowerCase();
    root.style.setProperty(`--md-sys-color-${kebab}`, value);
  });

  // Set standard convenience variables for layout
  root.style.setProperty('--bg-surface', colors.surface);
  root.style.setProperty('--bg-surface-container', colors.surfaceContainer);
  root.style.setProperty('--bg-surface-container-high', colors.surfaceContainerHigh);
  root.style.setProperty('--bg-surface-container-highest', colors.surfaceContainerHighest);
  root.style.setProperty('--text-on-surface', colors.onSurface);
  root.style.setProperty('--text-on-surface-variant', colors.onSurfaceVariant);
  root.style.setProperty('--color-primary', colors.primary);
  root.style.setProperty('--color-primary-container', colors.primaryContainer);
  root.style.setProperty('--text-on-primary-container', colors.onPrimaryContainer);
  root.style.setProperty('--border-outline', colors.outline);
  root.style.setProperty('--border-outline-variant', colors.outlineVariant);
}
